<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $brands = Brand::pluck('id', 'slug');
        $categories = Category::pluck('id', 'slug');

        $products = [
            [
                'brand_id' => $brands['tommy-hilfiger'],
                'category_id' => $categories['caballero'],
                'name' => 'Tommy Hilfiger Chronograph',
                'slug' => 'tommy-chronograph',
                'price' => 250000,
                'original_price' => 350000,
                'sku' => 'TH-CHR-001',
                'stock' => 15,
                'gender' => 'male',
                'movement' => 'Cuarzo',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'TH-CHR-001',
                    'estilo' => 'Elegante',
                    'garantia' => '2 años',
                    'origen' => 'Importado',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable 316L',
                    'tamano_caja' => '42 mm',
                    'grosor' => '11 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Mineral resistente a rayones',
                    'tipo_esfera' => 'Analógico con cronógrafo',
                    'color_esfera' => 'Azul',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Plateado',
                    'tipo_cierre' => 'Desplegable con seguro',
                    'resistencia_agua' => '5 ATM (50m)',
                    'funciones' => 'Cronógrafo, Fecha',
                ],
            ],
            [
                'brand_id' => $brands['casio'],
                'category_id' => $categories['caballero'],
                'name' => 'Casio G-Shock Digital',
                'slug' => 'casio-gshock',
                'price' => 180000,
                'original_price' => 220000,
                'sku' => 'CG-DIG-002',
                'stock' => 42,
                'gender' => 'male',
                'movement' => 'Cuarzo Digital',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'GA-2100-1A1',
                    'estilo' => 'Deportivo',
                    'garantia' => '1 año',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Digital',
                    'material_caja' => 'Resina',
                    'tamano_caja' => '48.5 mm',
                    'grosor' => '11.8 mm',
                    'forma_caja' => 'Octagonal',
                    'color_caja' => 'Negro',
                    'color_bisel' => 'Negro',
                    'color_esfera' => 'Negro',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Digital',
                    'correa_material' => 'Resina',
                    'correa_color' => 'Negro',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '20 ATM (200m)',
                    'funciones' => 'Cronómetro, Alarma, Luz LED, Mundial',
                ],
            ],
            [
                'brand_id' => $brands['titan'],
                'category_id' => $categories['caballero'],
                'name' => 'Titan Edge Automatic',
                'slug' => 'titan-edge',
                'price' => 320000,
                'sku' => 'TE-AUT-003',
                'stock' => 8,
                'gender' => 'male',
                'movement' => 'Automático',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'EDGE-AUT-001',
                    'estilo' => 'Ejecutivo',
                    'garantia' => '2 años',
                    'origen' => 'India',
                    'tipo_reloj' => 'Automático',
                    'material_caja' => 'Titanio',
                    'tamano_caja' => '40 mm',
                    'grosor' => '8.5 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'color_esfera' => 'Blanco',
                    'cristal' => 'Zafiro',
                    'tipo_esfera' => 'Analógico',
                    'correa_material' => 'Cuero',
                    'correa_color' => 'Marrón',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Fecha, Visualización de cuerda',
                ],
            ],
            [
                'brand_id' => $brands['guess'],
                'category_id' => $categories['dama'],
                'name' => 'Guess Ultra Thin',
                'slug' => 'guess-ultra',
                'price' => 195000,
                'sku' => 'GU-ULT-004',
                'stock' => 22,
                'gender' => 'female',
                'movement' => 'Cuarzo',
                'is_featured' => true,
                'is_new' => true,
                'specs' => [
                    'modelo_referencia' => 'GW0486L1',
                    'estilo' => 'Moderno',
                    'garantia' => '2 años',
                    'origen' => 'Importado',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '34 mm',
                    'grosor' => '7 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Dorado',
                    'color_bisel' => 'Dorado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Blanco perlado',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Dorado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Fecha',
                ],
            ],
            [
                'brand_id' => $brands['tommy-hilfiger'],
                'category_id' => $categories['dama'],
                'name' => 'Tommy Hilfiger Classic',
                'slug' => 'tommy-classic',
                'price' => 145000,
                'sku' => 'TH-CLS-005',
                'stock' => 18,
                'gender' => 'female',
                'movement' => 'Cuarzo',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'TH-CLS-005',
                    'estilo' => 'Clásico',
                    'garantia' => '2 años',
                    'origen' => 'Importado',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '32 mm',
                    'grosor' => '8 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Blanco',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Plateado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Fecha',
                ],
            ],
            [
                'brand_id' => $brands['citizen'],
                'category_id' => $categories['branded'],
                'name' => 'Citizen Eco-Drive',
                'slug' => 'citizen-eco',
                'price' => 450000,
                'sku' => 'CE-ECO-006',
                'stock' => 6,
                'gender' => 'male',
                'movement' => 'Eco-Drive',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'BM8180-03E',
                    'estilo' => 'Aventurero',
                    'garantia' => '3 años',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '36 mm',
                    'grosor' => '10 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Verde militar',
                    'correa_material' => 'Lona',
                    'correa_color' => 'Verde',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '10 ATM (100m)',
                    'funciones' => 'Fecha, Carga solar, Visualización de carga',
                ],
            ],
            [
                'brand_id' => $brands['casio'],
                'category_id' => $categories['caballero'],
                'name' => 'Casio Vintage',
                'slug' => 'casio-vintage',
                'price' => 89000,
                'original_price' => 120000,
                'sku' => 'CV-VIN-007',
                'stock' => 55,
                'gender' => 'unisex',
                'movement' => 'Cuarzo Digital',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'A168WG-9DF',
                    'estilo' => 'Retro',
                    'garantia' => '1 año',
                    'origen' => 'China',
                    'tipo_reloj' => 'Digital',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '36.3 mm',
                    'grosor' => '9.6 mm',
                    'forma_caja' => 'Rectangular',
                    'color_caja' => 'Dorado',
                    'color_bisel' => 'Dorado',
                    'color_esfera' => 'Negro',
                    'cristal' => 'Resina',
                    'tipo_esfera' => 'Digital',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Dorado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Cronómetro, Alarma, Luz LED, Calendario',
                ],
            ],
            [
                'brand_id' => $brands['michael-kors'],
                'category_id' => $categories['dama'],
                'name' => 'Michael Kors Access',
                'slug' => 'mk-access',
                'price' => 380000,
                'sku' => 'MK-ACC-008',
                'stock' => 11,
                'gender' => 'female',
                'movement' => 'Cuarzo',
                'is_featured' => false,
                'is_new' => true,
                'specs' => [
                    'modelo_referencia' => 'MK-ACC-008',
                    'estilo' => 'Moderno',
                    'garantia' => '2 años',
                    'origen' => 'Importado',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '38 mm',
                    'grosor' => '9 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Dorado rosado',
                    'color_bisel' => 'Dorado rosado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Rosado',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Dorado rosado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '5 ATM (50m)',
                    'funciones' => 'Fecha, Cronógrafo',
                ],
            ],
            [
                'brand_id' => $brands['timex'],
                'category_id' => $categories['caballero'],
                'name' => 'Timex Expedition',
                'slug' => 'timex-expedition',
                'price' => 130000,
                'sku' => 'TX-EXP-009',
                'stock' => 25,
                'gender' => 'male',
                'movement' => 'Cuarzo',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'T49905',
                    'estilo' => 'Aventurero',
                    'garantia' => '1 año',
                    'origen' => 'EE.UU.',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Resina',
                    'tamano_caja' => '40 mm',
                    'grosor' => '12 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Negro',
                    'color_bisel' => 'Negro',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Negro',
                    'correa_material' => 'Lona',
                    'correa_color' => 'Gris',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '10 ATM (100m)',
                    'funciones' => 'Fecha, Luz Indiglo',
                ],
            ],
            [
                'brand_id' => $brands['fossil'],
                'category_id' => $categories['branded'],
                'name' => 'Fossil Gen 6 Smartwatch',
                'slug' => 'fossil-gen6',
                'price' => 520000,
                'original_price' => 650000,
                'sku' => 'FS-GEN-010',
                'stock' => 4,
                'gender' => 'male',
                'movement' => 'Smartwatch',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'GEN6-001',
                    'estilo' => 'Tecnológico',
                    'garantia' => '1 año',
                    'origen' => 'EE.UU.',
                    'tipo_reloj' => 'Smartwatch',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '44 mm',
                    'grosor' => '12 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Carbón',
                    'color_bisel' => 'Carbón',
                    'color_esfera' => 'Negro',
                    'cristal' => 'Gorilla Glass',
                    'tipo_esfera' => 'Digital táctil',
                    'correa_material' => 'Silicón',
                    'correa_color' => 'Negro',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Wear OS, GPS, Ritmo cardíaco, NFC',
                ],
            ],
            [
                'brand_id' => $brands['citizen'],
                'category_id' => $categories['branded'],
                'name' => 'Citizen Tsuyosa',
                'slug' => 'citizen-tsuyosa',
                'price' => 550000,
                'sku' => 'CT-TSU-011',
                'stock' => 3,
                'gender' => 'unisex',
                'movement' => 'Automático',
                'is_featured' => false,
                'is_new' => true,
                'specs' => [
                    'modelo_referencia' => 'NJ0150-88X',
                    'estilo' => 'Elegante',
                    'garantia' => '3 años',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Automático',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '40 mm',
                    'grosor' => '12 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Zafiro',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Turquesa',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Plateado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '5 ATM (50m)',
                    'funciones' => 'Fecha, Visualización trasera',
                ],
            ],
            [
                'brand_id' => $brands['fossil'],
                'category_id' => $categories['dama'],
                'name' => 'Fossil Minimalist',
                'slug' => 'fossil-minimalist',
                'price' => 240000,
                'original_price' => 300000,
                'sku' => 'FS-MIN-012',
                'stock' => 14,
                'gender' => 'female',
                'movement' => 'Cuarzo',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'FS-MIN-012',
                    'estilo' => 'Minimalista',
                    'garantia' => '2 años',
                    'origen' => 'Importado',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '36 mm',
                    'grosor' => '8 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Dorado rosado',
                    'color_bisel' => 'Dorado rosado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Blanco',
                    'correa_material' => 'Malla de acero',
                    'correa_color' => 'Dorado rosado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Fecha',
                ],
            ],
            [
                'brand_id' => $brands['seiko'],
                'category_id' => $categories['caballero'],
                'name' => 'Seiko 5 Sports',
                'slug' => 'seiko-5',
                'price' => 420000,
                'sku' => 'SK-5SP-013',
                'stock' => 7,
                'gender' => 'male',
                'movement' => 'Automático',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'SRPD55K2',
                    'estilo' => 'Deportivo',
                    'garantia' => '2 años',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Automático',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '42.5 mm',
                    'grosor' => '13.4 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Negro',
                    'color_bisel' => 'Negro',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Negro',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Plateado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '10 ATM (100m)',
                    'funciones' => 'Fecha, Día, Visualización trasera',
                ],
            ],
            [
                'brand_id' => $brands['orient'],
                'category_id' => $categories['caballero'],
                'name' => 'Orient Bambino',
                'slug' => 'orient-bambino',
                'price' => 280000,
                'sku' => 'OR-BAM-014',
                'stock' => 9,
                'gender' => 'male',
                'movement' => 'Automático',
                'is_featured' => true,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'AC00009B',
                    'estilo' => 'Clásico',
                    'garantia' => '2 años',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Automático',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '40.5 mm',
                    'grosor' => '11.5 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico',
                    'color_esfera' => 'Crema',
                    'correa_material' => 'Cuero',
                    'correa_color' => 'Marrón',
                    'tipo_cierre' => 'Hebilla',
                    'resistencia_agua' => '3 ATM (30m)',
                    'funciones' => 'Fecha, Visualización trasera',
                ],
            ],
            [
                'brand_id' => $brands['casio'],
                'category_id' => $categories['caballero'],
                'name' => 'Casio Edifice',
                'slug' => 'casio-edifice',
                'price' => 210000,
                'original_price' => 260000,
                'sku' => 'CE-EDI-015',
                'stock' => 20,
                'gender' => 'male',
                'movement' => 'Cuarzo',
                'is_featured' => false,
                'is_new' => false,
                'specs' => [
                    'modelo_referencia' => 'EFV-540D-1AVUEF',
                    'estilo' => 'Deportivo-elegante',
                    'garantia' => '1 año',
                    'origen' => 'Japón',
                    'tipo_reloj' => 'Analógico',
                    'material_caja' => 'Acero inoxidable',
                    'tamano_caja' => '43 mm',
                    'grosor' => '11 mm',
                    'forma_caja' => 'Redonda',
                    'color_caja' => 'Plateado',
                    'color_bisel' => 'Plateado',
                    'cristal' => 'Mineral',
                    'tipo_esfera' => 'Analógico con cronógrafo',
                    'color_esfera' => 'Negro',
                    'correa_material' => 'Acero inoxidable',
                    'correa_color' => 'Plateado',
                    'tipo_cierre' => 'Desplegable',
                    'resistencia_agua' => '10 ATM (100m)',
                    'funciones' => 'Cronógrafo, Fecha, Taquímetro',
                ],
            ],
        ];

        foreach ($products as $product) {
            $product['description'] = "Reloj {$product['name']} original. " .
                ($product['specs']['estilo'] ?? 'Diseño clásico') .
                ". Movimiento " . strtolower($product['movement']) .
                ". Caja de " . ($product['specs']['material_caja'] ?? 'acero') .
                ". Resistencia al agua de " . ($product['specs']['resistencia_agua'] ?? '3 ATM') . ".";
            $product['short_description'] = "Reloj {$product['name']} — " .
                ($product['specs']['estilo'] ?? '') . ". " .
                $product['movement'] . ". " .
                ($product['specs']['tamano_caja'] ?? '');
            $product['published_at'] = now()->subDays(rand(1, 90));
            $product['min_stock'] = 5;

            Product::create($product);
        }
    }
}
